# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ frontend, backend ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: npm ci

      - name: Lint
        working-directory: ${{ matrix.project }}
        run: npm run lint

      - name: Run tests
        working-directory: ${{ matrix.project }}
        run: npm test -- --coverage
